name: Hello world # workflow name
on: [push] # event
jobs: # it can contain multiple jobs 
  hello: # job name
    runs-on: ubuntu-latest # where to run
    steps: 
     - name: print Hello worls
       run: echo "Hello, world!"